from setuptools import setup


# When https://github.com/pypa/setuptools/issues/1055 is fixed
# this can be moved to setup.cfg
setup(
    use_scm_version={
        'write_to': 'src/eturb/_version.py',
        'write_to_template': (
            '"""Autogenerated by setuptools_scm"""\n'
            '__version__ = "{version}"\n'
        ),
    }
)
